name: 11.20 - Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ./blog-list-api
        run: npm install
      - name: Check lint style
        working-directory: ./blog-list-api
        run: npm run lint
      - name: Run tests
        working-directory: ./blog-list-api
        run: npm run test
        env:
          NODE_ENV: test
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID_BACKEND }}?key=${{ secrets.RENDER_API_KEY_BACKEND }}

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: [deploy_backend]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ./blog-list-app
        run: npm install
      - name: Check lint style
        working-directory: ./blog-list-app
        run: npm run lint
      - name: Run build
        working-directory: ./blog-list-app
        run: npm run build
      - name: Install Playwright Browsers
        working-directory: ./blog-list-app
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./blog-list-app
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID_FRONTEND }}?key=${{ secrets.RENDER_API_KEY_FRONTEND }}

  tag_release:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    needs: [deploy_backend, deploy_frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
